version: '3.8'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: music-keycloak
    command: start-dev --import-realm
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8088:8080"
    depends_on:
      - keycloak-db
    networks:
      - music-net

  keycloak-db:
    image: postgres:16
    container_name: music-keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - music-net


  catalog-db:
    image: postgres:16
    container_name: music-catalog-db
    environment:
      - POSTGRES_DB=catalog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    networks:
      - music-net


  playlist-db:
    image: postgres:16
    container_name: music-playlist-db
    environment:
      - POSTGRES_DB=playlist_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    networks:
      - music-net

  redpanda:
    image: docker.io/redpandadata/redpanda:v23.1.2
    container_name: music-redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "9092:9092"
    networks:
      - music-net

  user-db:
    image: postgres:16
    container_name: music-user-db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5437:5432"
    networks:
      - music-net


networks:
  music-net:
    driver: bridge