quarkus.http.port=8083

quarkus.oidc.auth-server-url=http://localhost:8088/realms/music-streaming
quarkus.oidc.client-id=ui-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web_app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.devservices.enabled=false
quarkus.oidc.logout.path=/logout
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.roles.source=accesstoken
# Clients
quarkus.rest-client.playlist-api.url=http://localhost:8082
quarkus.rest-client.catalog-api.url=http://localhost:8081
quarkus.rest-client.user-api.url=http://localhost:8080