quarkus.http.port=8080
quarkus.oidc.devservices.enabled=false
quarkus.oidc.auth-server-url=http://localhost:8088/realms/music-streaming
quarkus.oidc.client-id=user-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=service