quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5437/user_db


quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.oidc.devservices.enabled=false
quarkus.oidc.auth-server-url=http://localhost:8088/realms/music-streaming
quarkus.oidc.client-id=user-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=service

mp.messaging.incoming.track-added-in.connector=smallrye-kafka
mp.messaging.incoming.track-added-in.topic=track-added-topic
mp.messaging.incoming.track-added-in.value.deserializer=com.bohdanbest.user.event.TrackAddedEventDeserializer

mp.messaging.outgoing.notifications-out.connector=smallrye-kafka
mp.messaging.outgoing.notifications-out.topic=notifications-topic
mp.messaging.outgoing.notifications-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.kafka.devservices.enabled=false