quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/playlist_db
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.devservices.enabled=false

quarkus.oidc.auth-server-url=http://localhost:8088/realms/music-streaming
quarkus.oidc.client-id=playlist-service
quarkus.oidc.devservices.enabled=false

quarkus.rest-client.catalog-api.url=http://localhost:8081

mp.messaging.outgoing.track-added-out.connector=smallrye-kafka
mp.messaging.outgoing.track-added-out.topic=track-added-topic
mp.messaging.outgoing.track-added-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.notifications-in.connector=smallrye-kafka
mp.messaging.incoming.notifications-in.topic=notifications-topic
mp.messaging.incoming.notifications-in.value.deserializer=com.bohdanbest.playlist.event.NotificationDeserializer